MyFinance.Core/MyFinance.Web/Models/RulesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MyFinance.Core.Model;

namespace MyFinance.Web.Models
{
    public class RulesViewModel
    {
        public DistributionRule Rule { get; set; }
        public List<DistributionRule> RuleList { get; set; }
    }
}

MyFinance.Core/MyFinance.Web/Controllers/RulesController.cs
using MyFinance.Core;
using MyFinance.Core.Model;
using MyFinance.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFinance.Web.Controllers
{
    public class RulesController : Controller
    {
        public PartialViewResult RulesPartial()
        {
            List<DistributionRule> ruleList = null;
            using (var queries = new FinancialQueries())
            {
                ruleList = queries.GetDistributionRules(User.Identity.Name);
            }

            RulesViewModel rvm = new RulesViewModel()
            {
                RuleList = ruleList,
                Rule = new DistributionRule()
            };

            return PartialView("RulesPartial", rvm);
        }

        public ActionResult AddRule(RulesViewModel rvm)
        {
            var rule = rvm.Rule;

            using (FinancialOperations fo = new FinancialOperations())
            {
                rule.UserId = User.Identity.Name;
                fo.AddRule(rule);
            }

            return RulesPartial();
        }

        public ActionResult RemoveRule(int ruleId)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                fo.RemoveRule(ruleId);
            }

            return RulesPartial();
        }

        public PartialViewResult RulesPercentagePartial(int ruleId)
        {
            List<DistributionPercentage> percentageList = null;
            List<Fund> fundList = null;
            List<Reserve> reserveList = null;
            using (var queries = new FinancialQueries())
            {
                fundList = queries.GetFunds(User.Identity.Name);
                reserveList = queries.GetReserves(User.Identity.Name);
                percentageList = queries.GetPercentageList(ruleId);
            }

            PercentageRuleViewModel prvm = new PercentageRuleViewModel()
            {
                DistributionPercentageList = percentageList,
                DistributionPercentage = new DistributionPercentage(),
                FundsList = GetListItem(fundList, "NONE"),
                ReservesList = GetListItem(reserveList)
            };

            prvm.DistributionPercentage.DistributionRuleId = ruleId;

            return PartialView("RulesPercentagePartial", prvm);
        }

        public ActionResult AddPercentageRule(PercentageRuleViewModel prvm)
        {
            var percentageRule = prvm.DistributionPercentage;

            if (percentageRule.FundID == -1)
                percentageRule.FundID = null;

            using (FinancialOperations fo = new FinancialOperations())
            {
                fo.AddPercentageRule(percentageRule);
            }

            return RulesPercentagePartial(prvm.DistributionPercentage.DistributionRuleId);
        }

        public ActionResult RemovePercentageRule(int percentageRuleId)
        {
            int ruleId;
            using (FinancialOperations fo = new FinancialOperations())
            {
                ruleId = fo.RemovePercentageRule(percentageRuleId);
            }

            return RulesPercentagePartial(ruleId);
        }

        private List<SelectListItem> GetListItem(List<Fund> list, string noneName = null)
        {
            List<SelectListItem> ret = new List<SelectListItem>();
            if (noneName != null)
                ret.Add(new SelectListItem() { Text = noneName, Value = "-1" });
            ret.AddRange(list.Select(f => new SelectListItem() { Text = f.Name, Value = f.ID.ToString() }));
            return ret;
        }

        private List<SelectListItem> GetListItem(List<Reserve> list, string noneName = null)
        {
            List<SelectListItem> ret = new List<SelectListItem>();
            if (noneName != null)
                ret.Add(new SelectListItem() { Text = noneName, Value = "-1" });
            ret.AddRange(list.Select(f => new SelectListItem() { Text = f.Name, Value = f.ID.ToString() }));
            return ret;
        }
	}
}

MyFinance.Core/MyFinance.Web/Views/Rules/AddPercentageRulePartial.cshtml
@model  MyFinance.Web.Models.PercentageRuleViewModel

@using (Html.BeginForm("AddPercentageRule", "Rules", FormMethod.Post, new { id = "addPercentageRuleForm" }))
{
    <div>
        @Html.HiddenFor(m => m.DistributionPercentage.DistributionRuleId, Model.DistributionPercentage.DistributionRuleId)
    </div>
    <div>
        @Html.LabelFor(m => m.DistributionPercentage.Fund)
        @Html.DropDownListFor(m => m.DistributionPercentage.FundID, Model.FundsList)
    </div>
    <div>
        @Html.LabelFor(m => m.DistributionPercentage.Reserve)
        @Html.DropDownListFor(m => m.DistributionPercentage.ReserveID, Model.ReservesList)
    </div>
    <div>
        @Html.LabelFor(m => m.DistributionPercentage.Percentage)
        @Html.TextBoxFor(m => m.DistributionPercentage.Percentage)
    </div>
}

MyFinance.Core/MyFinance.Web/Views/Rules/AddRulePartial.cshtml
@model  MyFinance.Web.Models.RulesViewModel

@using (Html.BeginForm("AddRule", "Rules", FormMethod.Post, new { id = "addRuleForm" }))
{
    <div>
        @Html.LabelFor(m => m.Rule.Name)
        @Html.TextBoxFor(m => m.Rule.Name)
    </div>
}

MyFinance.Core/MyFinance.Web/Views/Rules/RulesPartial.cshtml
@model MyFinance.Web.Models.RulesViewModel

<table id="rulesTable">
    <colgroup>
        <col />
    </colgroup>
    <thead>
        <tr>
            <th>Name</th>
            <th>Remove</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var entry in Model.RuleList)
            {
                <tr>
                    <td>
                        @entry.Name
                    </td>
                    <td>
                        <a type="button" href="#" onclick="loadPartial('@Url.Action("RulesPercentagePartial", "Rules")', { ruleId: @entry.Id }, '#setRulesPercentage');" class="btn btn-success">Set</a>
                        <a type="button" href="#" onclick="removeSelectedRow('@Url.Action("RemoveRule", "Rules")', { ruleId: @entry.Id });" class="btn btn-success">x</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<h3>Add a rule.</h3>
@Html.Partial("AddRulePartial", Model)
<input type="button" onclick="postAndUpdate('@Url.Action("AddRule", "Rules")', '#addRuleForm', '#dashboardContent', '#addFundModal');" value="Add Rule" class="btn btn-success" />

<div id="setRulesPercentage">

</div>

MyFinance.Core/MyFinance.Web/Views/Rules/RulesPercentagePartial.cshtml
@model MyFinance.Web.Models.PercentageRuleViewModel

<table id="rulesTable">
    <colgroup>
        <col />
    </colgroup>
    <thead>
        <tr>
            <th>Fund</th>
            <th>Reserve</th>
            <th>Percentage</th>
            <th>Remove</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var entry in Model.DistributionPercentageList)
            {
                <tr>
                    <td>
                        @(entry.Fund == null ? "-" : entry.Fund.Name)
                    </td>
                    <td>
                        @entry.Reserve.Name
                    </td>
                    <td>
                        @entry.Percentage
                    </td>
                    <td>
                        <a type="button" href="#" onclick="loadPartial('@Url.Action("RemovePercentageRule", "Rules")', { percentageRuleId: @entry.ID }, '#setRulesPercentage');" class="btn btn-success">x</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<h3>Add a percentage rule.</h3>
@Html.Partial("AddPercentageRulePartial", Model)
<input type="button" onclick="postAndUpdate('@Url.Action("AddPercentageRule", "Rules")', '#addPercentageRuleForm', '#setRulesPercentage', '#addFundModal');" value="Add Percentage Rule" class="btn btn-success" />