MyFinance.Core/MyFinance.Web/Models/ReserveViewModel.cs
using MyFinance.Core.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFinance.Web.Models
{
    public class ReserveViewModel
    {
        public Reserve Reserve { get; set; }
        public List<SelectListItem> TimeUnitList { get; set; }
        public List<Reserve> ReserveList { get; set; }
    }
}

MyFinance.Core/MyFinance.Web/Controllers/ReserveController.cs
using MyFinance.Core;
using MyFinance.Core.Model;
using MyFinance.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFinance.Web.Controllers
{
    public class ReserveController : Controller
    {
        //
        // GET: /Reserve/
        public PartialViewResult ReservesPartial()
        {
            ReserveViewModel rvm = new ReserveViewModel();
            using (FinancialQueries fq = new FinancialQueries())
            {
                rvm.ReserveList = fq.GetReserves(User.Identity.Name);
            }
            rvm.Reserve = new Reserve();
            rvm.TimeUnitList = GetListItemTimeUnit();

            return PartialView("ReservesPartial", rvm);
        }

        public ActionResult AddReserve(ReserveViewModel rvm)
        {
            var reserve = rvm.Reserve;

            using (FinancialOperations fo = new FinancialOperations())
            {
                reserve.UserId = User.Identity.Name;
                fo.AddReserve(reserve);
            }

            return ReservesPartial();
        }

        public ActionResult RemoveReserve(int reserveId)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                fo.RemoveReserve(reserveId);
            }

            return ReservesPartial();
        }

        private List<SelectListItem> GetListItemTimeUnit()
        {
            List<SelectListItem> ret = new List<SelectListItem>();

            ret.AddRange(Enum.GetNames(typeof(ETimeUnit))
                .Select(e => new SelectListItem() { Text = e, Value  = e }));

            return ret;
        }
	}
}

MyFinance.Core/MyFinance.Web/Views/Reserve/AddReservePartial.cshtml
@model  MyFinance.Web.Models.ReserveViewModel

@using (Html.BeginForm("AddReserve", "Reserves", FormMethod.Post, new { id = "addReserveForm" }))
{
    <div>
        @Html.LabelFor(m => m.Reserve.Name)
        @Html.TextBoxFor(m => m.Reserve.Name)
    </div>
    <div>
        @Html.LabelFor(m => m.Reserve.NameAbbreviation)
        @Html.TextBoxFor(m => m.Reserve.NameAbbreviation)
    </div>
    <div>
        @Html.LabelFor(m => m.Reserve.PeriodToWithdraw)
        @Html.TextBoxFor(m => m.Reserve.PeriodToWithdraw)
    </div>
    <div>
        @Html.LabelFor(m => m.Reserve.TimeUnit)
        @Html.DropDownListFor(m => m.Reserve.TimeUnit, Model.TimeUnitList)
    </div>
}

MyFinance.Core/MyFinance.Web/Views/Reserve/ReservesPartial.cshtml
@model MyFinance.Web.Models.ReserveViewModel

<div id="reservesTable" class="tbl tbl-striped">
    <div class="row tbl-header" style="font-weight: bold;">
        <div class="col-md-4">Name</div>
        <div class="col-md-3">Abbreviation</div>
        <div class="col-md-3">Period To withdraw</div>
        <div class="col-md-2 text-center">Remove</div>
    </div>
    <div style="height: 215px;" class="tbl-line">
        <div id="data-container" class="slimscroll">
            @if (Model != null)
            {
                foreach (var entry in Model.ReserveList)
                {
                    <div class="row tbl-row">
                        <div class="col-md-4">
                            @entry.Name
                        </div>
                        <div class="col-md-3">
                            @entry.NameAbbreviation
                        </div>
                        <div class="col-md-3">
                            @entry.PeriodToWithdraw @entry.TimeUnit
                        </div>
                        <div class="col-md-2 text-center">
                            <a href="#" onclick="loadPartial('@Url.Action("RemoveReserve", "Reserve")', { reserveId: @entry.ID }, '#dashboardContent'); return false;"><span class="glyphicon glyphicon-remove"></span></a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

<h3>Add a reserve.</h3>
@Html.Partial("AddReservePartial", Model)
<input type="button" onclick="postAndUpdate('@Url.Action("AddReserve", "Reserve")', '#addReserveForm', '#dashboardContent', '#addFundModal');" value="Add Reserve" class="btn btn-success" />
<script>
    $('.slimscroll').slimScroll({
        height: 'auto',
    });
</script>