MyFinance.Core/MyFinance.Web/Controllers/ManagerController.cs
using MyFinance.Core;
using MyFinance.Core.Model;
using MyFinance.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFinance.Web.Controllers
{
    public class ManagerController : Controller
    {
        //
        // GET: /Manager/
        public PartialViewResult SavingsAccountPartial()
        {
            var tvm = new TransactionViewModel();
            using (FinancialQueries queries = new FinancialQueries())
            {
                List<Fund> fundList = queries.GetFunds(User.Identity.Name);
                List<Reserve> reserveList = queries.GetReserves(User.Identity.Name);
                List<SelectListItem> distributionRuleItems = GetListItem(queries.GetDistributionRules(User.Identity.Name));

                tvm.TransactionList = queries.GetTransactions(null, null, DateTime.Today, User.Identity.Name);
                tvm.FundList = GetListItem(fundList, "TODOS");
                tvm.ReserveList = GetListItem(reserveList, "TODOS");
                tvm.Balance = tvm.TransactionList.Sum(t => t.Value);

                List<UpdateFundToDepositViewModel> fundsBalanceList = new List<UpdateFundToDepositViewModel>();
                fundsBalanceList.AddRange(
                    fundList.Select(
                        f => new UpdateFundToDepositViewModel()
                        { FundId = f.ID, FundName = f.Name }
                    )
                );

                DepositViewModel dvm = new DepositViewModel()
                {
                    FundList = GetListItem(fundList, "NENHUM"),
                    ReserveList = GetListItem(reserveList, "NENHUM"),
                    DistributionRuleList = distributionRuleItems,
                    Date = DateTime.Today,
                    fundsBalanceList = fundsBalanceList
                };
                tvm.DepositViewModel = dvm;

                WithdrawViewModel wvm = new WithdrawViewModel()
                {
                    FundList = GetListItem(fundList),
                    ReserveList = GetListItem(reserveList),
                    Date = DateTime.Today
                };
                tvm.WithdrawViewModel = wvm;

                UpdateBalanceViewModel ubvm = new UpdateBalanceViewModel()
                {
                    FundList = GetListItem(fundList),
                    Date = DateTime.Today
                };
                tvm.UpdateBalanceViewModel = ubvm;
            }

            return PartialView("SavingsAccountPartial", tvm);
        }

        [HttpPost]
        public ActionResult GetTransationList(int? fundId, int? reserveId = null)
        {
            if (fundId == -1) fundId = null;
            if (reserveId == -1) reserveId = null;
            using (FinancialQueries queries = new FinancialQueries())
            {
                List<Transaction> transactionList = queries.GetTransactions(
                    fundId, reserveId, DateTime.Today, User.Identity.Name);
                return Json(new
                {
                    balance = transactionList.Sum(t => t.Value).ToString("0.00"),
                    transactionList = RenderPartialViewToString("TransactionListPartial", transactionList)
                });
            }
        }

        public ActionResult GetFundsFromDepositRule(int depositRuleId)
        {
            List<UpdateFundToDepositViewModel> ubvmList = new List<UpdateFundToDepositViewModel>();
            using (FinancialQueries fq = new FinancialQueries())
            {
                if (depositRuleId != -1)
                {
                    int[] funds = fq.GetDistributionRule(depositRuleId).DistributionPercentages.Where(dp => dp.FundID != null).Select(dp => dp.FundID.Value).Distinct().ToArray();
                    return Json(funds);
                }
            }

            return Json(new { });
        }

        [HttpPost]
        public ActionResult UpdateBalance(UpdateBalanceViewModel ubvm)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                fo.UpdateProfits(ubvm.Value, ubvm.SelectedFundId, ubvm.Date, User.Identity.Name);
            }

            return SavingsAccountPartial();
        }

        [HttpPost]
        public ActionResult Deposit(DepositViewModel dvm)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                Dictionary<int, decimal> balancesBeforeDeposit = new Dictionary<int,decimal>();
                foreach (var fb in dvm.fundsBalanceList)
                    if (fb.Value.HasValue)
                        balancesBeforeDeposit.Add(fb.FundId, fb.Value.Value);

                fo.Deposit(dvm.Value, balancesBeforeDeposit, dvm.Date, dvm.Origin, dvm.SelectedFundId,
                    dvm.SelectedReserveId, dvm.SelectedDistriutionRuleId, User.Identity.Name);
            }

            return SavingsAccountPartial();
        }

        //[HttpPost]
        public ActionResult Withdraw(WithdrawViewModel wvm)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                fo.WithDraw(wvm.Value, wvm.Date, wvm.Origin, wvm.SelectedFundId, wvm.SelectedReserveId, User.Identity.Name);
            }

            return SavingsAccountPartial();
        }

        private List<SelectListItem> GetListItem(List<Fund> list, string noneName = null)
        {
            List<SelectListItem> ret = new List<SelectListItem>();
            if (noneName != null)
                ret.Add(new SelectListItem() { Text = noneName, Value = "-1" });
            ret.AddRange(list.Select(f => new SelectListItem() { Text = f.Name, Value = f.ID.ToString() }));
            return ret;
        }

        private List<SelectListItem> GetListItem(List<DistributionRule> list)
        {
            List<SelectListItem> ret = new List<SelectListItem>();
            ret.Add(new SelectListItem() { Text = "NENHUM", Value = "-1" });
            ret.AddRange(list.Select(f => new SelectListItem() { Text = f.Name, Value = f.Id.ToString() }));
            return ret;
        }

        private List<SelectListItem> GetListItem(List<Reserve> list, string noneName = null)
        {
            List<SelectListItem> ret = new List<SelectListItem>();
            if (noneName != null)
                ret.Add(new SelectListItem() { Text = noneName, Value = "-1" });
            ret.AddRange(list.Select(f => new SelectListItem() { Text = f.Name, Value = f.ID.ToString() }));
            return ret;
        }

        protected string RenderPartialViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;

            using (var sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);

                return sw.GetStringBuilder().ToString();
            }
        }

    }
}

MyFinance.Core/MyFinance.Web/Views/Manager/DepositModal.cshtml
@model MyFinance.Web.Models.DepositViewModel
<div id="depositModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>
                <h5 class="modal-title">Make a deposit</h5>
            </div>
            <div class="modal-body">
                @Html.Partial("DepositPartial", Model)
            </div>
            <div class="modal-footer">
                <input type="button" onclick="postAndUpdateManager('@Url.Action("Deposit", "Manager")', '#depositForm', '#dashboardContent', '#depositModal');" value="Deposit" class="btn btn-success" />
                <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>

MyFinance.Core/MyFinance.Web/Views/Manager/DepositPartial.cshtml
@model MyFinance.Web.Models.DepositViewModel

@using (Html.BeginForm("Deposit", "Manager", FormMethod.Post, new { id = "depositForm", @class = "form-horizontal", role = "form" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Origin, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.Origin, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SelectedDistriutionRuleId, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.SelectedDistriutionRuleId, Model.DistributionRuleList, new { id = "depositRuleSelect", @class = "select-block" })
        </div>
    </div>
    <div id="combos">
        <div class="form-group">
            @Html.LabelFor(m => m.SelectedFundId, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.DropDownListFor(m => m.SelectedFundId, Model.FundList, new { id = "fundSelect", @class = "select-block" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SelectedReserveId, new { @class = "col-md-4 control-label" })
            <div class="col-md-8">
                @Html.DropDownListFor(m => m.SelectedReserveId, Model.ReserveList, new { @class = "select-block" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-4 control-label" })
        <div class="col-md-8">
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control datepicker" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Value, new { @class = "col-md-4 control-label" })
        <div class="col-md-8 input-group">
            @{
                if (Model.Value == 0M)
                {
                    Model.Value = 0.00M;
                }
            }
            <span class="input-group-addon">$</span>
            @Html.TextBoxFor(m => m.Value, new { @class = "form-control value-mask" })
        </div>

    </div>

    <div id="fbList">
        @for (int i = 0; i < Model.fundsBalanceList.Count; i++)
        {
            <div id="fb@(Model.fundsBalanceList[i].FundId)" style="display: none" class="form-group">
                @Html.Label(Model.fundsBalanceList[i].FundName, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @{
                    if (Model.fundsBalanceList[i].Value == 0M || Model.fundsBalanceList[i].Value == null)
                        {
                            Model.fundsBalanceList[i].Value = 0.00M;
                        }
                    }
                    <div class="input-group">
                        <span class="input-group-addon">$</span>
                        @Html.TextBoxFor(m => m.fundsBalanceList[i].Value, new { @class = "form-control value-mask" })
                    </div>
                    @Html.HiddenFor(m => m.fundsBalanceList[i].FundId)
                    <p class="help-block">Saldo atual (antes do depósito).</p>
                </div>
            </div>
        }
    </div>
}

<script>
    $(document).ready(function () {
        $('#depositRuleSelect').on("change", depositSelectChange);
        $('#fundSelect').on("change", fundSelectChange);
    });

    function depositSelectChange() {

        if ($('#depositRuleSelect').val() == '-1')
            $('#combos').slideDown();
        else $('#combos').slideUp();

        $.post('@Url.Action("GetFundsFromDepositRule", "Manager")',
            { depositRuleId: $('#depositRuleSelect').val() },
            function (data) {
                $('#fbList').children().each(function (i) {
                    divId = this.id;
                    slideDown = false;
                    jQuery.each(data, function () {
                        if ("fb" + this == divId)
                            slideDown = true;
                    });
                    if (slideDown) $(this).slideDown();
                    else {
                        $('#fundsBalanceList_' + i + '__Value').val('');
                        $(this).slideUp();
                    }
                });
            });
    }

    function fundSelectChange() {

        $('#fbList').children().each(function (i) {
            if ('fb' + $('#fundSelect').val() == this.id)
                $(this).slideDown();
            else {
                $('#fundsBalanceList_' + i + '__Value').val('');
                $(this).slideUp();

            }
        });

    }
</script>

MyFinance.Core/MyFinance.Web/Views/Manager/SavingsAccountPartial.cshtml
@model MyFinance.Web.Models.TransactionViewModel
<div class="frame">
    <div class="row ">
        <div class="col-md-3">
            @Html.Label("Filtrar por fundo:", new { @class = "label" })
            @Html.DropDownList("FundList", Model.FundList, new { id = "fundList", @class = "select-block" })
        </div>
        <div class="col-md-3">
            @Html.Label("Filtar por objetivo:", new { @class = "label" })
            @Html.DropDownList("ReserveList", Model.ReserveList, new { id = "reserveList", @class = "select-block" })
        </div>
    </div>
</div>
<br />
<div id="transactionList">
    @Html.Partial("TransactionListPartial", Model.TransactionList)
</div>
<div class="row tbl-footer">
    <div class="col-md-2 col-md-offset-8" style="padding-left: 24px;">
        Balance:
    </div>
    <div class="col-md-2 text-right @(Model.Balance > 0 ? "text-info" : "text-danger")" id="balance">
        @Model.Balance.ToString("#,0.00")
    </div>
</div>
<div class="btn-group btn-group-justified">
    <a type="button" data-toggle="modal" href="#depositModal" class="btn btn-primary"><span class="ficon-deposit"></span> Depositar</a>
    <a type="button" data-toggle="modal" href="#depositModal" class="btn btn-primary"><span class="ficon-transfer"></span> Transferir</a>
    <a type="button" data-toggle="modal" href="#withdrawModal" class="btn btn-primary"><span class="ficon-withdraw"></span> Resgatar</a>
    <a type="button" data-toggle="modal" href="#updateBalanceModal" class="btn btn-primary"><span class="ficon-balance"></span> Atualizar Saldo</a>
    <a type="button" data-toggle="modal" href="#undoLastOperation" class="btn btn-primary"><span class="ficon-balance"></span> Desfazer</a>
</div>

<div id="depositModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>
                <h5 class="modal-title">Faça um depósito.</h5>
            </div>
            <div class="modal-body">
                @Html.Partial("DepositPartial", Model.DepositViewModel)
            </div>
            <div class="modal-footer">
                <input type="button" onclick="postAndUpdateManager('@Url.Action("Deposit", "Manager")', '#depositForm', '#dashboardContent', '#depositModal');" value="Deposit" class="btn btn-success" />
                <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>

<div id="withdrawModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>
                <h5 class="modal-title" style="line-height: 1;">Withdraw <br /><small class="text-muted" style="font-size: 0.6em;">Are you sure?</small></h5>
            </div>
            <div class="modal-body">
                @Html.Partial("WithdrawPartial", Model.WithdrawViewModel)
            </div>
            <div class="modal-footer">
                <input type="button" onclick="postAndUpdateManager('@Url.Action("Withdraw", "Manager")', '#withdrawForm', '#dashboardContent', '#withdrawModal');" value="Withdraw" class="btn btn-success" />
                <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>

<div id="updateBalanceModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>
                <h5 class="modal-title" style="line-height: 1;">
                    Atualize seu saldo<br />
                <small class="text-muted" style="font-size: 0.6em;">Informe o saldo atual do fundo escolhido para atualizar os seus rendimentos.</small></h5>
            </div>
            <div class="modal-body">
                @Html.Partial("UpdateFundBalancePartial", Model.UpdateBalanceViewModel)
            </div>
            <div class="modal-footer">
                <input type="button" onclick="postAndUpdateManager('@Url.Action("UpdateBalance", "Manager")', '#updateBalanceForm', '#dashboardContent', '#updateBalanceModal');" value="Update Balance" class="btn btn-success" />
                <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
<script src="~/scripts/viewscripts/Dashboard/Index.js"></script>
<script>
    $(function () {
        $("select").selectpicker({ style: 'btn-primary', menuStyle: 'dropdown-inverse' });
    });
</script>

MyFinance.Core/MyFinance.Web/Views/Manager/TransactionListPartial.cshtml
@model List<MyFinance.Core.Model.Transaction>

<div id="transactionWrap" class="tbl tbl-striped" >
    <div class="row tbl-header" style="font-weight: bold;">
        <div class="col-xs-2">Data</div>
        <div class="col-xs-3">Objetivo</div>
        <div class="col-xs-3">Fundo</div>
        <div class="col-xs-2">Origem</div>
        <div class="col-xs-2 text-right" style="padding-right: 30px;">Valor</div>
    </div>
    <div style="height: 215px;" class="tbl-line">
        <div id="data-container" class="slimscroll">
            @if (Model != null)
            {
                foreach (var entry in Model)
                {
                    <div class="row tbl-row">
                        <div class="col-xs-2 tbl-col">@entry.Date.ToShortDateString()</div>
                        <div class="col-xs-3 tbl-col" title="@entry.Reserve.Name">@entry.Reserve.Name</div>
                        <div class="col-xs-3 tbl-col" title="@entry.Fund.Name">@entry.Fund.Name</div>
                        <div class="col-xs-2 tbl-col" title="@(entry.ProfitId.HasValue ? "Rendimentos" : entry.Origins)">@(entry.ProfitId.HasValue ? "Rendimentos" : entry.Origins)</div>
                        <div class="col-xs-2 tbl-col text-right @(entry.Value > 0 ? "text-info" : "text-danger")" style="padding-right: 30px;">@entry.Value.ToString("#,0.00")</div>
                    </div>
                }
            }
        </div>
    </div>
</div>

<script>
    $('.slimscroll').slimScroll({
        height: 'auto',
    });
</script>

MyFinance.Core/MyFinance.Web/Views/Manager/UpdateFundBalancePartial.cshtml
@model MyFinance.Web.Models.UpdateBalanceViewModel

@using (Html.BeginForm("UpdateBalance", "Manager", FormMethod.Post, new { id = "updateBalanceForm", @class = "form-horizontal", role = "form" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.SelectedFundId, new { @class = "col-md-2 control-label" })
        <div class="col-md-9">
            @Html.DropDownListFor(m => m.SelectedFundId, Model.FundList, htmlAttributes: new { @class = "select-block" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control datepicker" })
        </div>
    </div>
    if (Model.Value == 0M)
    {
        Model.Value = 0.00M;
    }
    <div class="form-group">
        @Html.LabelFor(m => m.Value, new { @class = "col-md-2 control-label" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.Value, new { @class = "form-control value-mask" })
        </div>
    </div>
}

MyFinance.Core/MyFinance.Web/Views/Manager/WithdrawPartial.cshtml
@model MyFinance.Web.Models.WithdrawViewModel

@using (Html.BeginForm("Withdraw", "Manager", FormMethod.Post, new { id = "withdrawForm", @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Origin, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Origin, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SelectedFundId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.SelectedFundId, Model.FundList, new { @class = "select-block" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SelectedReserveId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.SelectedReserveId, Model.ReserveList, new { @class = "select-block" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.Date, "{0:d}", new { @class = "form-control datepicker" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Value, new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.TextBoxFor(m => m.Value, new { @class = "form-control" })
        </div>
    </div>
}