MyFinance.Core/MyFinance.Web/Models/FundsViewModel.cs
using MyFinance.Core.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyFinance.Web.Models
{
    public class FundsViewModel
    {
        public Fund Fund { get; set; }
        public List<Fund> FundList { get; set; }
    }
}

MyFinance.Core/MyFinance.Web/Controllers/FundsController.cs
using MyFinance.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyFinance.Core.Model;
using MyFinance.Core;

namespace MyFinance.Web.Controllers
{
    public class FundsController : Controller
    {
        //
        // GET: /Funds/
        public PartialViewResult FundsPartial()
        {
            FundsViewModel fvm = new FundsViewModel();
            using (FinancialQueries fq = new FinancialQueries())
            {
                fvm.FundList = fq.GetFunds(User.Identity.Name);
            }

            fvm.Fund = new Fund();
            
            return PartialView("FundsPartial", fvm);
        }

        public ActionResult AddFund(Fund fund)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                fund.UserId = User.Identity.Name;
                fo.AddFund(fund);
            }

            return FundsPartial();
        }

        public ActionResult RemoveFund(int fundId)
        {
            using (FinancialOperations fo = new FinancialOperations())
            {
                fo.RemoveFund(fundId);
            }

            return FundsPartial();
        }
	}
}

MyFinance.Core/MyFinance.Web/Views/Funds/AddFundPartial.cshtml
@model  MyFinance.Core.Model.Fund

@using (Html.BeginForm("AddFund", "Funds", FormMethod.Post, new { id = "addFundForm" }))
{
    <div>
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div>
        @Html.LabelFor(m => m.NameAbbreviation)
        @Html.TextBoxFor(m => m.NameAbbreviation)
    </div>
}

MyFinance.Core/MyFinance.Web/Views/Funds/FundsPartial.cshtml
@model MyFinance.Web.Models.FundsViewModel

<div id="fundsTable" class="tbl tbl-striped">
    <div class="row tbl-header" style="font-weight: bold;">
        <div class="col-md-6">Name</div>
        <div class="col-md-3">Abbreviation</div>
        <div class="col-md-3 text-center">Remove</div>
    </div>
    <div style="height: 215px;" class="tbl-line">
        <div id="data-container" class="slimscroll">
            @if (Model != null)
            {
                foreach (var entry in Model.FundList)
                {
                    <div class="row tbl-row">
                        <div class="col-md-6">@entry.Name</div>
                        <div class="col-md-3">@entry.NameAbbreviation</div>
                        <div class="col-md-3 text-center">
                            <a href="#" onclick="loadPartial('@Url.Action("RemoveFund", "Funds")', { fundId: @entry.ID }, '#dashboardContent'); return false;"><span class="glyphicon glyphicon-remove"></span></a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

<h3>Add a fund.</h3>
@Html.Partial("AddFundPartial", Model.Fund)
<input type="button" onclick="postAndUpdate('@Url.Action("AddFund", "Funds")', '#addFundForm', '#dashboardContent', '#addFundModal');" value="Add Fund" class="btn btn-success" />

<script>
    $('.slimscroll').slimScroll({
        height: 'auto',
    });
</script>